"""Mock data catalog modeled after real IATA / Amadeus flight distribution APIs.

Features:
- Multi-airport metropolitan cities (London LON: LHR, LGW, STN, LCY, LTN; Paris PAR: CDG, ORY, BVA; etc.).
- Complete airline profiles with custom cabin multipliers, discount policies, and baggage rules.
- Scheduled direct and hub-and-spoke connecting flights with weekend/peak multipliers.
"""

from typing import Any

# --- Worldwide Airports (including Multi-Airport Metros) ---
MOCK_AIRPORTS: list[dict[str, Any]] = [
    # London Metropolitan Area (LON)
    {
        "iata_code": "LHR",
        "name": "London Heathrow Airport",
        "city": "London",
        "city_code": "LON",
        "country": "United Kingdom",
        "country_code": "GB",
        "timezone": "Europe/London",
        "terminals": ["T2", "T3", "T4", "T5"],
    },
    {
        "iata_code": "LGW",
        "name": "London Gatwick Airport",
        "city": "London",
        "city_code": "LON",
        "country": "United Kingdom",
        "country_code": "GB",
        "timezone": "Europe/London",
        "terminals": ["North", "South"],
    },
    {
        "iata_code": "STN",
        "name": "London Stansted Airport",
        "city": "London",
        "city_code": "LON",
        "country": "United Kingdom",
        "country_code": "GB",
        "timezone": "Europe/London",
        "terminals": ["Main Terminal"],
    },
    {
        "iata_code": "LCY",
        "name": "London City Airport",
        "city": "London",
        "city_code": "LON",
        "country": "United Kingdom",
        "country_code": "GB",
        "timezone": "Europe/London",
        "terminals": ["Main Terminal"],
    },
    {
        "iata_code": "LTN",
        "name": "London Luton Airport",
        "city": "London",
        "city_code": "LON",
        "country": "United Kingdom",
        "country_code": "GB",
        "timezone": "Europe/London",
        "terminals": ["Main Terminal"],
    },
    # Paris Metropolitan Area (PAR)
    {
        "iata_code": "CDG",
        "name": "Paris Charles de Gaulle Airport",
        "city": "Paris",
        "city_code": "PAR",
        "country": "France",
        "country_code": "FR",
        "timezone": "Europe/Paris",
        "terminals": ["T1", "T2E", "T2F", "T3"],
    },
    {
        "iata_code": "ORY",
        "name": "Paris Orly Airport",
        "city": "Paris",
        "city_code": "PAR",
        "country": "France",
        "country_code": "FR",
        "timezone": "Europe/Paris",
        "terminals": ["Orly 1", "Orly 2", "Orly 3", "Orly 4"],
    },
    {
        "iata_code": "BVA",
        "name": "Beauvais-Tillé Airport",
        "city": "Paris",
        "city_code": "PAR",
        "country": "France",
        "country_code": "FR",
        "timezone": "Europe/Paris",
        "terminals": ["T1", "T2"],
    },
    # New York Metropolitan Area (NYC)
    {
        "iata_code": "JFK",
        "name": "John F. Kennedy International Airport",
        "city": "New York",
        "city_code": "NYC",
        "country": "United States",
        "country_code": "US",
        "timezone": "America/New_York",
        "terminals": ["T1", "T4", "T5", "T7", "T8"],
    },
    {
        "iata_code": "EWR",
        "name": "Newark Liberty International Airport",
        "city": "New York",
        "city_code": "NYC",
        "country": "United States",
        "country_code": "US",
        "timezone": "America/New_York",
        "terminals": ["Terminal A", "Terminal B", "Terminal C"],
    },
    {
        "iata_code": "LGA",
        "name": "LaGuardia Airport",
        "city": "New York",
        "city_code": "NYC",
        "country": "United States",
        "country_code": "US",
        "timezone": "America/New_York",
        "terminals": ["Terminal A", "Terminal B", "Terminal C"],
    },
    # Tokyo Metropolitan Area (TYO)
    {
        "iata_code": "HND",
        "name": "Tokyo Haneda Airport",
        "city": "Tokyo",
        "city_code": "TYO",
        "country": "Japan",
        "country_code": "JP",
        "timezone": "Asia/Tokyo",
        "terminals": ["T1", "T2", "T3"],
    },
    {
        "iata_code": "NRT",
        "name": "Narita International Airport",
        "city": "Tokyo",
        "city_code": "TYO",
        "country": "Japan",
        "country_code": "JP",
        "timezone": "Asia/Tokyo",
        "terminals": ["T1", "T2", "T3"],
    },
    # Vietnam Major Hubs
    {
        "iata_code": "SGN",
        "name": "Tan Son Nhat International Airport",
        "city": "Ho Chi Minh City",
        "city_code": "SGN",
        "country": "Vietnam",
        "country_code": "VN",
        "timezone": "Asia/Ho_Chi_Minh",
        "terminals": ["T1", "T2"],
    },
    {
        "iata_code": "HAN",
        "name": "Noi Bai International Airport",
        "city": "Hanoi",
        "city_code": "HAN",
        "country": "Vietnam",
        "country_code": "VN",
        "timezone": "Asia/Ho_Chi_Minh",
        "terminals": ["T1", "T2"],
    },
    {
        "iata_code": "DAD",
        "name": "Da Nang International Airport",
        "city": "Da Nang",
        "city_code": "DAD",
        "country": "Vietnam",
        "country_code": "VN",
        "timezone": "Asia/Ho_Chi_Minh",
        "terminals": ["T1", "T2"],
    },
    # Other Global Hubs
    {
        "iata_code": "SIN",
        "name": "Singapore Changi Airport",
        "city": "Singapore",
        "city_code": "SIN",
        "country": "Singapore",
        "country_code": "SG",
        "timezone": "Asia/Singapore",
        "terminals": ["T1", "T2", "T3", "T4"],
    },
    {
        "iata_code": "BKK",
        "name": "Suvarnabhumi Airport",
        "city": "Bangkok",
        "city_code": "BKK",
        "country": "Thailand",
        "country_code": "TH",
        "timezone": "Asia/Bangkok",
        "terminals": ["Main Terminal"],
    },
    {
        "iata_code": "FRA",
        "name": "Frankfurt Airport",
        "city": "Frankfurt",
        "city_code": "FRA",
        "country": "Germany",
        "country_code": "DE",
        "timezone": "Europe/Berlin",
        "terminals": ["T1", "T2"],
    },
    {
        "iata_code": "DXB",
        "name": "Dubai International Airport",
        "city": "Dubai",
        "city_code": "DXB",
        "country": "United Arab Emirates",
        "country_code": "AE",
        "timezone": "Asia/Dubai",
        "terminals": ["T1", "T2", "T3"],
    },
    {
        "iata_code": "SYD",
        "name": "Sydney Kingsford Smith Airport",
        "city": "Sydney",
        "city_code": "SYD",
        "country": "Australia",
        "country_code": "AU",
        "timezone": "Australia/Sydney",
        "terminals": ["T1", "T2", "T3"],
    },
    {
        "iata_code": "SFO",
        "name": "San Francisco International Airport",
        "city": "San Francisco",
        "city_code": "SFO",
        "country": "United States",
        "country_code": "US",
        "timezone": "America/Los_Angeles",
        "terminals": ["T1", "T2", "T3", "International"],
    },
    {
        "iata_code": "LAX",
        "name": "Los Angeles International Airport",
        "city": "Los Angeles",
        "city_code": "LAX",
        "country": "United States",
        "country_code": "US",
        "timezone": "America/Los_Angeles",
        "terminals": ["TBIT", "T1", "T4", "T5", "T6", "T7"],
    },
]

# --- Supported Airlines and Dynamic Service/Pricing Rules ---
MOCK_AIRLINES: dict[str, dict[str, Any]] = {
    "BA": {
        "iata_code": "BA",
        "name": "British Airways",
        "alliance": "oneworld",
        "baggage_policy": {
            "cabin_bags_included": 1,
            "cabin_bag_weight_kg": 10.0,
            "checked_bags_included": 1,
            "checked_bag_weight_kg": 23.0,
        },
        "pricing_policy": {
            "cabin_multipliers": {
                "ECONOMY": 1.00,
                "PREMIUM_ECONOMY": 1.50,
                "BUSINESS": 2.50,
                "FIRST": 4.20,
            },
            "child_discount_ratio": 0.20,
            "infant_discount_ratio": 0.90,
            "seat_selection_fee": 18.0,
            "extra_checked_bag_fee": 45.0,
            "tax_and_fee_rate": 0.16,
        },
    },
    "AF": {
        "iata_code": "AF",
        "name": "Air France",
        "alliance": "SkyTeam",
        "baggage_policy": {
            "cabin_bags_included": 1,
            "cabin_bag_weight_kg": 12.0,
            "checked_bags_included": 1,
            "checked_bag_weight_kg": 23.0,
        },
        "pricing_policy": {
            "cabin_multipliers": {
                "ECONOMY": 1.00,
                "PREMIUM_ECONOMY": 1.48,
                "BUSINESS": 2.45,
                "FIRST": 4.10,
            },
            "child_discount_ratio": 0.22,
            "infant_discount_ratio": 0.90,
            "seat_selection_fee": 16.0,
            "extra_checked_bag_fee": 42.0,
            "tax_and_fee_rate": 0.15,
        },
    },
    "VN": {
        "iata_code": "VN",
        "name": "Vietnam Airlines",
        "alliance": "SkyTeam",
        "baggage_policy": {
            "cabin_bags_included": 1,
            "cabin_bag_weight_kg": 12.0,
            "checked_bags_included": 1,
            "checked_bag_weight_kg": 23.0,
        },
        "pricing_policy": {
            "cabin_multipliers": {
                "ECONOMY": 1.00,
                "PREMIUM_ECONOMY": 1.40,
                "BUSINESS": 2.30,
                "FIRST": 3.80,
            },
            "child_discount_ratio": 0.25,
            "infant_discount_ratio": 0.90,
            "seat_selection_fee": 12.0,
            "extra_checked_bag_fee": 38.0,
            "tax_and_fee_rate": 0.12,
        },
    },
    "SQ": {
        "iata_code": "SQ",
        "name": "Singapore Airlines",
        "alliance": "Star Alliance",
        "baggage_policy": {
            "cabin_bags_included": 1,
            "cabin_bag_weight_kg": 7.0,
            "checked_bags_included": 2,
            "checked_bag_weight_kg": 23.0,
        },
        "pricing_policy": {
            "cabin_multipliers": {
                "ECONOMY": 1.00,
                "PREMIUM_ECONOMY": 1.55,
                "BUSINESS": 2.70,
                "FIRST": 4.60,
            },
            "child_discount_ratio": 0.20,
            "infant_discount_ratio": 0.90,
            "seat_selection_fee": 20.0,
            "extra_checked_bag_fee": 55.0,
            "tax_and_fee_rate": 0.14,
        },
    },
    "JL": {
        "iata_code": "JL",
        "name": "Japan Airlines",
        "alliance": "oneworld",
        "baggage_policy": {
            "cabin_bags_included": 1,
            "cabin_bag_weight_kg": 10.0,
            "checked_bags_included": 2,
            "checked_bag_weight_kg": 23.0,
        },
        "pricing_policy": {
            "cabin_multipliers": {
                "ECONOMY": 1.00,
                "PREMIUM_ECONOMY": 1.50,
                "BUSINESS": 2.50,
                "FIRST": 4.20,
            },
            "child_discount_ratio": 0.25,
            "infant_discount_ratio": 0.90,
            "seat_selection_fee": 15.0,
            "extra_checked_bag_fee": 50.0,
            "tax_and_fee_rate": 0.13,
        },
    },
    "EK": {
        "iata_code": "EK",
        "name": "Emirates",
        "alliance": "Emirates Group",
        "baggage_policy": {
            "cabin_bags_included": 1,
            "cabin_bag_weight_kg": 7.0,
            "checked_bags_included": 2,
            "checked_bag_weight_kg": 23.0,
        },
        "pricing_policy": {
            "cabin_multipliers": {
                "ECONOMY": 1.00,
                "PREMIUM_ECONOMY": 1.60,
                "BUSINESS": 2.80,
                "FIRST": 4.80,
            },
            "child_discount_ratio": 0.25,
            "infant_discount_ratio": 0.90,
            "seat_selection_fee": 22.0,
            "extra_checked_bag_fee": 60.0,
            "tax_and_fee_rate": 0.14,
        },
    },
    "DL": {
        "iata_code": "DL",
        "name": "Delta Air Lines",
        "alliance": "SkyTeam",
        "baggage_policy": {
            "cabin_bags_included": 1,
            "cabin_bag_weight_kg": 9.0,
            "checked_bags_included": 1,
            "checked_bag_weight_kg": 23.0,
        },
        "pricing_policy": {
            "cabin_multipliers": {
                "ECONOMY": 1.00,
                "PREMIUM_ECONOMY": 1.44,
                "BUSINESS": 2.35,
                "FIRST": 3.70,
            },
            "child_discount_ratio": 0.15,
            "infant_discount_ratio": 0.90,
            "seat_selection_fee": 15.0,
            "extra_checked_bag_fee": 35.0,
            "tax_and_fee_rate": 0.15,
        },
    },
    "UA": {
        "iata_code": "UA",
        "name": "United Airlines",
        "alliance": "Star Alliance",
        "baggage_policy": {
            "cabin_bags_included": 1,
            "cabin_bag_weight_kg": 8.0,
            "checked_bags_included": 1,
            "checked_bag_weight_kg": 23.0,
        },
        "pricing_policy": {
            "cabin_multipliers": {
                "ECONOMY": 1.00,
                "PREMIUM_ECONOMY": 1.42,
                "BUSINESS": 2.30,
                "FIRST": 3.75,
            },
            "child_discount_ratio": 0.15,
            "infant_discount_ratio": 0.90,
            "seat_selection_fee": 15.0,
            "extra_checked_bag_fee": 35.0,
            "tax_and_fee_rate": 0.15,
        },
    },
}

# --- Scheduled Direct Routes Catalog ---
MOCK_DIRECT_SCHEDULES: list[dict[str, Any]] = [
    # === London (LON) <-> Paris (PAR) Routes ===
    # British Airways: LHR -> CDG (Morning)
    {
        "flight_number": "BA-304",
        "carrier_code": "BA",
        "origin": "LHR",
        "origin_terminal": "T5",
        "destination": "CDG",
        "destination_terminal": "T2A",
        "departure_time": "07:15",
        "duration_minutes": 80,
        "aircraft": "Airbus A320neo",
        "base_economy_price": 95.0,
        "initial_available_seats": 24,
        "weekend_multiplier": 1.15,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 25.0,
            "change_allowed": True,
            "change_fee": 15.0,
            "terms": "BA Euro Traveller: Refundable minus fee up to 24h before departure.",
        },
    },
    # British Airways: LHR -> CDG (Afternoon)
    {
        "flight_number": "BA-314",
        "carrier_code": "BA",
        "origin": "LHR",
        "origin_terminal": "T5",
        "destination": "CDG",
        "destination_terminal": "T2A",
        "departure_time": "14:30",
        "duration_minutes": 80,
        "aircraft": "Airbus A321neo",
        "base_economy_price": 105.0,
        "initial_available_seats": 18,
        "weekend_multiplier": 1.15,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 25.0,
            "change_allowed": True,
            "change_fee": 15.0,
            "terms": "BA Euro Traveller standard refundable terms.",
        },
    },
    # British Airways: LHR -> CDG (Evening)
    {
        "flight_number": "BA-326",
        "carrier_code": "BA",
        "origin": "LHR",
        "origin_terminal": "T5",
        "destination": "CDG",
        "destination_terminal": "T2A",
        "departure_time": "19:40",
        "duration_minutes": 80,
        "aircraft": "Airbus A320neo",
        "base_economy_price": 88.0,
        "initial_available_seats": 22,
        "weekend_multiplier": 1.10,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 25.0,
            "change_allowed": True,
            "change_fee": 15.0,
            "terms": "BA Euro Traveller standard refundable terms.",
        },
    },
    # British Airways: CDG -> LHR (Morning)
    {
        "flight_number": "BA-305",
        "carrier_code": "BA",
        "origin": "CDG",
        "origin_terminal": "T2A",
        "destination": "LHR",
        "destination_terminal": "T5",
        "departure_time": "09:30",
        "duration_minutes": 80,
        "aircraft": "Airbus A320neo",
        "base_economy_price": 95.0,
        "initial_available_seats": 26,
        "weekend_multiplier": 1.15,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 25.0,
            "change_allowed": True,
            "change_fee": 15.0,
            "terms": "BA Euro Traveller standard refundable terms.",
        },
    },
    # British Airways: CDG -> LHR (Afternoon)
    {
        "flight_number": "BA-315",
        "carrier_code": "BA",
        "origin": "CDG",
        "origin_terminal": "T2A",
        "destination": "LHR",
        "destination_terminal": "T5",
        "departure_time": "16:45",
        "duration_minutes": 80,
        "aircraft": "Airbus A321neo",
        "base_economy_price": 102.0,
        "initial_available_seats": 20,
        "weekend_multiplier": 1.15,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 25.0,
            "change_allowed": True,
            "change_fee": 15.0,
            "terms": "BA Euro Traveller standard refundable terms.",
        },
    },
    # Air France: LHR -> CDG (Morning)
    {
        "flight_number": "AF-1681",
        "carrier_code": "AF",
        "origin": "LHR",
        "origin_terminal": "T4",
        "destination": "CDG",
        "destination_terminal": "T2E",
        "departure_time": "10:30",
        "duration_minutes": 85,
        "aircraft": "Airbus A220-300",
        "base_economy_price": 94.0,
        "initial_available_seats": 22,
        "weekend_multiplier": 1.12,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 25.0,
            "change_allowed": True,
            "change_fee": 15.0,
            "terms": "Air France European standard fare.",
        },
    },
    # Air France: CDG -> LHR (Morning)
    {
        "flight_number": "AF-1680",
        "carrier_code": "AF",
        "origin": "CDG",
        "origin_terminal": "T2E",
        "destination": "LHR",
        "destination_terminal": "T4",
        "departure_time": "08:20",
        "duration_minutes": 85,
        "aircraft": "Airbus A220-300",
        "base_economy_price": 92.0,
        "initial_available_seats": 25,
        "weekend_multiplier": 1.12,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 25.0,
            "change_allowed": True,
            "change_fee": 15.0,
            "terms": "Air France European standard fare.",
        },
    },
    # Air France: CDG -> LHR (Afternoon)
    {
        "flight_number": "AF-1780",
        "carrier_code": "AF",
        "origin": "CDG",
        "origin_terminal": "T2E",
        "destination": "LHR",
        "destination_terminal": "T4",
        "departure_time": "15:10",
        "duration_minutes": 85,
        "aircraft": "Airbus A321",
        "base_economy_price": 98.0,
        "initial_available_seats": 20,
        "weekend_multiplier": 1.12,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 25.0,
            "change_allowed": True,
            "change_fee": 15.0,
            "terms": "Air France standard refundable terms.",
        },
    },
    # British Airways: LGW -> ORY (Morning)
    {
        "flight_number": "BA-802",
        "carrier_code": "BA",
        "origin": "LGW",
        "origin_terminal": "South",
        "destination": "ORY",
        "destination_terminal": "Orly 1",
        "departure_time": "09:00",
        "duration_minutes": 75,
        "aircraft": "Airbus A320",
        "base_economy_price": 79.0,
        "initial_available_seats": 30,
        "weekend_multiplier": 1.10,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 20.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Standard short-haul refundable fare.",
        },
    },
    # Air France: ORY -> LGW (Evening)
    {
        "flight_number": "AF-1882",
        "carrier_code": "AF",
        "origin": "ORY",
        "origin_terminal": "Orly 2",
        "destination": "LGW",
        "destination_terminal": "South",
        "departure_time": "18:30",
        "duration_minutes": 75,
        "aircraft": "Airbus A320",
        "base_economy_price": 82.0,
        "initial_available_seats": 28,
        "weekend_multiplier": 1.10,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 20.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Standard short-haul refundable fare.",
        },
    },
    # === Transatlantic: London (LHR) <-> New York (JFK) ===
    {
        "flight_number": "BA-112",
        "carrier_code": "BA",
        "origin": "JFK",
        "origin_terminal": "T8",
        "destination": "LHR",
        "destination_terminal": "T5",
        "departure_time": "18:30",
        "duration_minutes": 420,
        "aircraft": "Boeing 777-300ER",
        "base_economy_price": 490.0,
        "initial_available_seats": 29,
        "weekend_multiplier": 1.18,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 100.0,
            "change_allowed": True,
            "change_fee": 45.0,
            "terms": "BA Transatlantic standard refundable rules.",
        },
    },
    {
        "flight_number": "BA-117",
        "carrier_code": "BA",
        "origin": "LHR",
        "origin_terminal": "T5",
        "destination": "JFK",
        "destination_terminal": "T8",
        "departure_time": "11:20",
        "duration_minutes": 485,
        "aircraft": "Boeing 777-300ER",
        "base_economy_price": 495.0,
        "initial_available_seats": 27,
        "weekend_multiplier": 1.18,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 100.0,
            "change_allowed": True,
            "change_fee": 45.0,
            "terms": "BA Transatlantic standard fare.",
        },
    },
    # === London (LHR) <-> Singapore (SIN) ===
    {
        "flight_number": "SQ-306",
        "carrier_code": "SQ",
        "origin": "SIN",
        "origin_terminal": "T3",
        "destination": "LHR",
        "destination_terminal": "T2",
        "departure_time": "01:10",
        "duration_minutes": 835,
        "aircraft": "Airbus A380-800",
        "base_economy_price": 620.0,
        "initial_available_seats": 38,
        "weekend_multiplier": 1.15,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 120.0,
            "change_allowed": True,
            "change_fee": 40.0,
            "terms": "SQ standard refundable terms.",
        },
    },
    {
        "flight_number": "SQ-305",
        "carrier_code": "SQ",
        "origin": "LHR",
        "origin_terminal": "T2",
        "destination": "SIN",
        "destination_terminal": "T3",
        "departure_time": "14:50",
        "duration_minutes": 810,
        "aircraft": "Airbus A380-800",
        "base_economy_price": 630.0,
        "initial_available_seats": 34,
        "weekend_multiplier": 1.15,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 120.0,
            "change_allowed": True,
            "change_fee": 40.0,
            "terms": "SQ standard refundable terms.",
        },
    },
    # === Vietnam Domestic Routes (SGN <-> HAN <-> DAD) ===
    {
        "flight_number": "VN-210",
        "carrier_code": "VN",
        "origin": "SGN",
        "origin_terminal": "T1",
        "destination": "HAN",
        "destination_terminal": "T1",
        "departure_time": "06:30",
        "duration_minutes": 130,
        "aircraft": "Airbus A350-900",
        "base_economy_price": 75.0,
        "initial_available_seats": 24,
        "weekend_multiplier": 1.10,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 20.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Refundable up to 24h prior to departure with standard fee.",
        },
    },
    {
        "flight_number": "VN-214",
        "carrier_code": "VN",
        "origin": "SGN",
        "origin_terminal": "T1",
        "destination": "HAN",
        "destination_terminal": "T1",
        "departure_time": "11:00",
        "duration_minutes": 130,
        "aircraft": "Boeing 787-9 Dreamliner",
        "base_economy_price": 85.0,
        "initial_available_seats": 18,
        "weekend_multiplier": 1.12,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 20.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Refundable up to 24h prior to departure.",
        },
    },
    {
        "flight_number": "VN-226",
        "carrier_code": "VN",
        "origin": "SGN",
        "origin_terminal": "T1",
        "destination": "HAN",
        "destination_terminal": "T1",
        "departure_time": "20:15",
        "duration_minutes": 130,
        "aircraft": "Airbus A321neo",
        "base_economy_price": 70.0,
        "initial_available_seats": 25,
        "weekend_multiplier": 1.05,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 20.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Standard refundable terms.",
        },
    },
    # SGN <-> DAD (Da Nang Direct Flights)
    {
        "flight_number": "VN-120",
        "carrier_code": "VN",
        "origin": "SGN",
        "origin_terminal": "T1",
        "destination": "DAD",
        "destination_terminal": "T1",
        "departure_time": "08:15",
        "duration_minutes": 80,
        "aircraft": "Airbus A321neo",
        "base_economy_price": 70.0,
        "initial_available_seats": 20,
        "weekend_multiplier": 1.05,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 15.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Standard refundable terms.",
        },
    },
    {
        "flight_number": "VN-122",
        "carrier_code": "VN",
        "origin": "SGN",
        "origin_terminal": "T1",
        "destination": "DAD",
        "destination_terminal": "T1",
        "departure_time": "10:30",
        "duration_minutes": 80,
        "aircraft": "Airbus A321neo",
        "base_economy_price": 75.0,
        "initial_available_seats": 15,
        "weekend_multiplier": 1.05,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 15.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Standard refundable terms.",
        },
    },
    {
        "flight_number": "VN-128",
        "carrier_code": "VN",
        "origin": "SGN",
        "origin_terminal": "T1",
        "destination": "DAD",
        "destination_terminal": "T1",
        "departure_time": "17:45",
        "duration_minutes": 80,
        "aircraft": "Airbus A321neo",
        "base_economy_price": 95.0,
        "initial_available_seats": 10,
        "weekend_multiplier": 1.10,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 20.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Standard refundable terms.",
        },
    },
    {
        "flight_number": "VN-121",
        "carrier_code": "VN",
        "origin": "DAD",
        "origin_terminal": "T1",
        "destination": "SGN",
        "destination_terminal": "T1",
        "departure_time": "09:00",
        "duration_minutes": 80,
        "aircraft": "Airbus A321neo",
        "base_economy_price": 70.0,
        "initial_available_seats": 22,
        "weekend_multiplier": 1.05,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 15.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Standard refundable terms.",
        },
    },
    {
        "flight_number": "VN-211",
        "carrier_code": "VN",
        "origin": "HAN",
        "origin_terminal": "T1",
        "destination": "SGN",
        "destination_terminal": "T1",
        "departure_time": "07:30",
        "duration_minutes": 130,
        "aircraft": "Airbus A350-900",
        "base_economy_price": 75.0,
        "initial_available_seats": 22,
        "weekend_multiplier": 1.10,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 20.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Refundable up to 24h prior to departure.",
        },
    },
    {
        "flight_number": "VN-215",
        "carrier_code": "VN",
        "origin": "HAN",
        "origin_terminal": "T1",
        "destination": "SGN",
        "destination_terminal": "T1",
        "departure_time": "14:15",
        "duration_minutes": 130,
        "aircraft": "Boeing 787-9 Dreamliner",
        "base_economy_price": 82.0,
        "initial_available_seats": 20,
        "weekend_multiplier": 1.10,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 20.0,
            "change_allowed": True,
            "change_fee": 10.0,
            "terms": "Refundable terms apply.",
        },
    },
    # === SGN <-> SIN (Singapore Hub Transit) ===
    {
        "flight_number": "VN-651",
        "carrier_code": "VN",
        "origin": "SGN",
        "origin_terminal": "T2",
        "destination": "SIN",
        "destination_terminal": "T3",
        "departure_time": "09:10",
        "duration_minutes": 130,
        "aircraft": "Airbus A321neo",
        "base_economy_price": 115.0,
        "initial_available_seats": 16,
        "weekend_multiplier": 1.12,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 35.0,
            "change_allowed": True,
            "change_fee": 20.0,
            "terms": "Refundable with cancellation fee up to 48h prior.",
        },
    },
    {
        "flight_number": "SQ-178",
        "carrier_code": "SQ",
        "origin": "SGN",
        "origin_terminal": "T2",
        "destination": "SIN",
        "destination_terminal": "T2",
        "departure_time": "12:15",
        "duration_minutes": 130,
        "aircraft": "Boeing 787-10",
        "base_economy_price": 140.0,
        "initial_available_seats": 25,
        "weekend_multiplier": 1.08,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 40.0,
            "change_allowed": True,
            "change_fee": 25.0,
            "terms": "SQ standard refundable ticket with 2 checked bags included.",
        },
    },
    {
        "flight_number": "SQ-177",
        "carrier_code": "SQ",
        "origin": "SIN",
        "origin_terminal": "T2",
        "destination": "SGN",
        "destination_terminal": "T2",
        "departure_time": "09:50",
        "duration_minutes": 130,
        "aircraft": "Boeing 787-10",
        "base_economy_price": 138.0,
        "initial_available_seats": 22,
        "weekend_multiplier": 1.08,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 40.0,
            "change_allowed": True,
            "change_fee": 25.0,
            "terms": "Refundable with SQ policy.",
        },
    },
    # === Tokyo (TYO) <-> US / Asia Routes ===
    {
        "flight_number": "JL-002",
        "carrier_code": "JL",
        "origin": "HND",
        "origin_terminal": "T3",
        "destination": "SFO",
        "destination_terminal": "International",
        "departure_time": "19:45",
        "duration_minutes": 575,
        "aircraft": "Boeing 777-300ER",
        "base_economy_price": 680.0,
        "initial_available_seats": 26,
        "weekend_multiplier": 1.16,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 120.0,
            "change_allowed": True,
            "change_fee": 50.0,
            "terms": "Full refund minus cancellation fee before departure.",
        },
    },
    {
        "flight_number": "JL-001",
        "carrier_code": "JL",
        "origin": "SFO",
        "origin_terminal": "International",
        "destination": "HND",
        "destination_terminal": "T3",
        "departure_time": "13:30",
        "duration_minutes": 660,
        "aircraft": "Boeing 777-300ER",
        "base_economy_price": 680.0,
        "initial_available_seats": 24,
        "weekend_multiplier": 1.16,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 120.0,
            "change_allowed": True,
            "change_fee": 50.0,
            "terms": "Full refund minus cancellation fee before departure.",
        },
    },
    {
        "flight_number": "JL-752",
        "carrier_code": "JL",
        "origin": "SGN",
        "origin_terminal": "T2",
        "destination": "NRT",
        "destination_terminal": "T2",
        "departure_time": "07:55",
        "duration_minutes": 335,
        "aircraft": "Boeing 787-8",
        "base_economy_price": 340.0,
        "initial_available_seats": 20,
        "weekend_multiplier": 1.14,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 65.0,
            "change_allowed": True,
            "change_fee": 35.0,
            "terms": "JAL International fare with 2 checked bags included.",
        },
    },
    # === US Domestic (LAX <-> JFK) ===
    {
        "flight_number": "DL-301",
        "carrier_code": "DL",
        "origin": "LAX",
        "origin_terminal": "T2",
        "destination": "JFK",
        "destination_terminal": "T4",
        "departure_time": "07:00",
        "duration_minutes": 325,
        "aircraft": "Boeing 767-300ER",
        "base_economy_price": 180.0,
        "initial_available_seats": 28,
        "weekend_multiplier": 1.12,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 30.0,
            "change_allowed": True,
            "change_fee": 0.0,
            "terms": "Delta domestic refundable with cancellation fee.",
        },
    },
    {
        "flight_number": "DL-302",
        "carrier_code": "DL",
        "origin": "JFK",
        "origin_terminal": "T4",
        "destination": "LAX",
        "destination_terminal": "T2",
        "departure_time": "17:15",
        "duration_minutes": 360,
        "aircraft": "Boeing 767-300ER",
        "base_economy_price": 185.0,
        "initial_available_seats": 22,
        "weekend_multiplier": 1.12,
        "cancellation_policy": {
            "refundable": True,
            "cancellation_fee": 30.0,
            "change_allowed": True,
            "change_fee": 0.0,
            "terms": "Delta domestic refundable terms.",
        },
    },
]
